arch: aarch64
cpus: 4
disk: 128GiB
memory: 8GiB
mountType: virtiofs
vmType: vz

containerd:
  system: false
  user: false
  archives: []

images:
  - arch: aarch64
    digest: sha512:645b7710b16c2687f0f77ab612684a48630e546acdf03335652bf1fd9958276f250e8fa6859f35c184df35414fd00a95823e2703303ff90932ab8f21bd54a8c0
    location: https://cloud.debian.org/images/cloud/bookworm/20230802-1460/debian-12-genericcloud-arm64-20230802-1460.qcow2

mounts:
  - location: "~"
    writable: true
  - location: "/tmp/lima"
    writable: true

networks:
  - vzNAT: true

rosetta:
  binfmt: true
  enabled: true

ssh:
  forwardAgent: true
  forwardX11: true
  forwardX11Trusted: true
  loadDotSSHPubKeys: true
  localPort: 60022
