arch: aarch64
cpus: 4
disk: 256GiB
memory: 8GiB
mountType: virtiofs
vmType: vz

containerd:
  system: false
  user: false
  archives: []

images:
  - arch: aarch64
    digest: sha256:3405f30db62441c18258c21c01754addeb4dfdf9714d151f042942d223ab3865
    location: https://repo.almalinux.org/almalinux/9.1/cloud/aarch64/images/AlmaLinux-9-GenericCloud-9.1-20221118.aarch64.qcow2

mounts:
  - location: "~"
    writable: true
  - location: "/tmp/lima"
    writable: true

networks:
  - vzNAT: true

rosetta:
  binfmt: true
  enabled: true

ssh:
  forwardAgent: true
  forwardX11: true
  forwardX11Trusted: true
  loadDotSSHPubKeys: true
  localPort: 60022
