# vi: set ft=yaml.ansible :
---
- name: Preflight
  hosts: all
  become: true
  roles:
    - role: system
  tasks:
    - name: Add /usr/local/bin to sudo PATH
      ansible.builtin.copy:
        content: "Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
        dest: /etc/sudoers.d/localpath
        mode: "0440"

    # Maybe later https://github.com/kubernetes/kubeadm/issues/279
    - name: Set SELinux to permissive
      block:
        - name: Set SELinux Config
          ansible.builtin.copy:
            dest: /etc/selinux/config
            mode: "0440"
            content: |
              SELINUX=permissive
              SELINUXTYPE=targeted

        - name: Set SELinux to permissive
          changed_when: false # Meh too tedious to check
          failed_when: setenforce.rc != 0
          register: setenforce
          ansible.builtin.command: /usr/sbin/setenforce 0

    - name: Update
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest

    - name: Install necessary packages
      ansible.builtin.dnf:
        state: present
        name:
          - conntrack-tools
          - container-selinux
          - epel-release
          - ethtool
          - iproute-tc
          - iptables-nft
          - ipvsadm
          - socat
          - slirp4netns

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install container runtime
  hosts: all
  become: true
  roles:
    - role: runc
      vars:
        version: 1.1.4
    - role: cni_plugins
      vars:
        version: 1.2.0
    - role: containerd
      vars:
        containerd_version: 1.7.0
        nerdctl_version: 1.2.1
    - role: rootlesskit
      vars:
        version: 1.1.0

- name: Install kubernetes
  hosts: all
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  vars:
    kubernetes_version: 1.26.3
    pod_cidr: 10.244.0.0/16
  roles:
    - role: cri_tools
      vars:
        version: 1.26.1
    - role: kubernetes
      vars:
        version: "{{ kubernetes_version }}"
  tasks:
    - name: Start services
      loop:
        - containerd
        - kubelet
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started

    - name: Install kubeadm configuration
      ansible.builtin.template:
        dest: /etc/kubeadm/config.yml
        mode: "0644"
        src: kubeadm.yml

    - name: Initialize cluster
      changed_when: init.rc == 0
      failed_when: init.rc != 0 and "/etc/kubernetes/manifests/kube-apiserver.yaml already exists" not in init.stderr
      register: init
      ansible.builtin.command: >
        kubeadm init
        --config=/etc/kubeadm/config.yml

    - name: Install manifests
      loop:
        - flannel.yml
        - local-path-storage.yml
      ansible.builtin.template:
        dest: /etc/kubernetes/{{ item }}
        mode: "0644"
        src: "{{ item }}"

    - name: Apply manifests
      changed_when: '" configured " in apply.stdout or " created " in apply.stdout'
      failed_when: apply.rc != 0
      register: apply
      loop:
        - flannel.yml
        - local-path-storage.yml
      ansible.builtin.command: >
        kubectl apply -f
        /etc/kubernetes/{{ item }}

    - name: Untaint node
      changed_when: untaint.rc == 0 and "untainted" in untaint.stdout
      failed_when: untaint.rc != 0 and "not found" not in untaint.stderr
      register: untaint
      ansible.builtin.command: >
        kubectl taint node
        {{ ansible_hostname }}
        node-role.kubernetes.io/control-plane:NoSchedule-
