# vi: set ft=yaml.ansible :
---
- name: Preflight
  hosts: all
  become: true
  roles:
    - role: system
  tasks:
    - name: Update
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Install necessary packages
      ansible.builtin.apt:
        state: present
        name:
          # - conntrack-tools
          - dbus-user-session
          - ethtool
          # - iproute-tc
          - conntrack
          - nftables
          - ipvsadm
          - socat
          - slirp4netns
          - uidmap

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install container runtime
  hosts: all
  become: true
  roles:
    - role: runc
      vars:
        version: 1.1.4
    - role: cni_plugins
      vars:
        version: 1.2.0
    - role: containerd
      vars:
        containerd_version: 1.7.0
        nerdctl_version: 1.2.1
    - role: rootlesskit
      vars:
        version: 1.1.0

- name: Install kubernetes
  hosts: all
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  vars:
    kubernetes_version: 1.26.3
    pod_cidr: 10.244.0.0/16
  roles:
    - role: cri_tools
      vars:
        version: 1.26.1
    - role: kubernetes
      vars:
        version: "{{ kubernetes_version }}"
  tasks:
    - name: Start services
      loop:
        - containerd
        - kubelet
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started

    - name: Install kubeadm configuration
      ansible.builtin.template:
        dest: /etc/kubeadm/config.yml
        mode: "0644"
        src: kubeadm.yml

    - name: Initialize cluster
      changed_when: init.rc == 0
      failed_when: init.rc != 0 and "/etc/kubernetes/manifests/kube-apiserver.yaml already exists" not in init.stderr
      register: init
      ansible.builtin.command: >
        kubeadm init
        --config=/etc/kubeadm/config.yml

    - name: Install manifests
      loop:
        - flannel.yml
        - local-path-storage.yml
      ansible.builtin.template:
        dest: /etc/kubernetes/{{ item }}
        mode: "0644"
        src: "{{ item }}"

    - name: Apply manifests
      changed_when: '" configured " in apply.stdout or " created " in apply.stdout'
      failed_when: apply.rc != 0
      register: apply
      loop:
        - flannel.yml
        - local-path-storage.yml
      ansible.builtin.command: >
        kubectl apply -f
        /etc/kubernetes/{{ item }}

    - name: Untaint node
      changed_when: untaint.rc == 0 and "untainted" in untaint.stdout
      failed_when: untaint.rc != 0 and "not found" not in untaint.stderr
      register: untaint
      ansible.builtin.command: >
        kubectl taint node
        {{ ansible_hostname }}
        node-role.kubernetes.io/control-plane:NoSchedule-
