# vi: set ft=yaml.ansible :
---
- name: Download rootlesskit archive
  ansible.builtin.get_url:
    checksum: "sha256:\
      https://github.com/rootless-containers/rootlesskit/releases/download/v{{ version }}/\
      SHA256SUMS"
    dest: /tmp
    group: root
    mode: "0644"
    owner: root
    url:
      "https://github.com/rootless-containers/rootlesskit/releases/download/v{{ version }}/\
      rootlesskit-{{ ansible_architecture }}.tar.gz"

- name: Extract rootlesskit archive
  ansible.builtin.unarchive:
    dest: "{{ prefix }}/bin"
    group: root
    mode: "0755"
    owner: root
    remote_src: true
    src: /tmp/rootlesskit-{{ ansible_architecture }}.tar.gz

- name: Retrieve user information
  register: user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present

- name: Ensure user linger
  ansible.builtin.include_tasks: linger.yml

- name: Ensure directories
  become: false
  ansible.builtin.file:
    mode: "0755"
    path: "{{ user.home }}/.config/systemd/user"
    state: directory

- name: Install service definition
  become: false
  ansible.builtin.template:
    dest: "{{ user.home }}/.config/systemd/user/containerd.service"
    mode: "0644"
    src: containerd.service

- name: Enable user containerd service
  become: false
  when: enable_service
  ansible.builtin.systemd:
    enabled: true
    name: containerd
    scope: user
    state: started
