# vi: set ft=yaml.ansible :
---
- name: Create necessary directories
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
  ansible.builtin.file:
    mode: "0755"
    path: "{{ item }}"
    state: directory

- name: Download archive
  ansible.builtin.get_url:
    checksum: "sha256:\
      https://github.com/containernetworking/plugins/releases/download/v{{ version }}/\
      cni-plugins-linux-{{ go_arch }}-v{{ version }}.tgz.sha256"
    dest: /tmp
    mode: "0644"
    url:
      "https://github.com/containernetworking/plugins/releases/download/v{{ version }}/\
      cni-plugins-linux-{{ go_arch }}-v{{ version }}.tgz"

- name: Extract archive
  ansible.builtin.unarchive:
    dest: /opt/cni/bin
    mode: "0755"
    remote_src: true
    src: /tmp/cni-plugins-linux-{{ go_arch }}-v{{ version }}.tgz
