# vi: set ft=yaml.ansible :
---
- name: Download runc
  ansible.builtin.get_url:
    checksum: "sha256:\
      https://github.com/opencontainers/runc/releases/download/v{{ version }}/\
      runc.sha256sum"
    dest: "{{ prefix }}/bin/runc"
    mode: "0755"
    url:
      "https://github.com/opencontainers/runc/releases/download/v{{ version }}/\
      runc.{{ go_arch }}"
